### ISSUE TITLE
Unexpect token import in tns_modules/nativescript-urlhandler/urlhandler.js

### ISSUE THREAD

**Issue by scavezze** [hypery2k/nativescript-urlhandler#15]
```
import * as application from 'application';
import { getCallback, extractAppURL } from './urlhandler.common';
export { handleOpenURL } from './urlhandler.common';
var lastReceivedData = null;
application.android.on(application.AndroidApplication.activityResumedEvent, function (args) {
    var data = args.activity.getIntent().getData();
    if (data !== lastReceivedData) {
        try {
            if (new String(args.activity.getIntent().getAction()).valueOf() === new String(android.content.Intent.ACTION_VIEW).valueOf()) {
                getCallback()(extractAppURL(data));
                lastReceivedData = data;
            }
        }
        catch (e) {
            console.error('Unknown error during getting App URL data', e);
        }
    }
});
```
I am very new to typescript but i think that with a target of es5 those import statements should be require statements.  I think

**Comment by hypery2k** [comment]
do you have a specific error?
You can use ES5 with another module loader then commons, so in this case es2015 [module](https://github.com/hypery2k/nativescript-urlhandler/blob/master/tsconfig.json#L4)

**Comment by hypery2k** [comment]
Version [0.4.0](https://github.com/hypery2k/nativescript-urlhandler/releases/tag/v0.4.0) is available

**Comment by scavezze** [comment]
The error is that the nativescript app fails to start because it doesn't recognize import so i get a unexpected token error.  the issue is that if i make a brand new app and add your plugin i don't get this error so I am guessing maybe a different plugin or something is interfering.  I am new to typescript and nativescript so i will keep looking into it.

**Comment by hypery2k** [comment]
okay, if this plugin is causing any issue feel free to open a new issue

**Comment by scavezze** [comment]
after the change you made last night everything is working now for some reason getData() is null but that is probably my issue thanks

**Comment by hypery2k** [comment]
you're welcome
