### ISSUE TITLE
applicationOpenURLSourceApplicationAnnotation is deprecated

### ISSUE THREAD

**Issue by speigg** [hypery2k/nativescript-urlhandler#23]
`applicationOpenURLSourceApplicationAnnotation` is deprecated, and doesn't get called when the app is launched from a url (only if the app is already running). `application:openURL:options:` gets called in both situations, and should be used instead.

**Comment by hypery2k** [comment]
Thanks for the hint. Will change the implementation

**Comment by speigg** [comment]
Another hint: I found that you have to implement `applicationWillFinishLaunchingWithOptions` as well in order for `applicationOpenURLOptions` to be called at launch. Specifically, `applicationWillFinishLaunchingWithOptions` has to return `true`. I'll submit a PR soon.

**Comment by hypery2k** [comment]
any PR is welcome

**Comment by speigg** [comment]
Fixed with #31
