### ISSUE TITLE
Bundling using nativescript-dev-webpack fails

### ISSUE THREAD

**Issue by rezonjov** [hypery2k/nativescript-urlhandler#49]
Hey, the plugin will fail when bundled using webpack. 

The fix is to set `"noEmitHelpers"` to `true` at the `tsconfig.json` as mentioned here [https://github.com/NativeScript/nativescript-dev-webpack/issues/70#issuecomment-279085077](link)

So far it's working fine for me. 

in case you need my environment:

- node: 6.11
- nativescript version: 2.3.2
- nativescript-dev-webpack: 0.6.3

**Comment by hypery2k** [comment]
ok, will put it to the docs.

Thanks for the hint

**Comment by marksutt** [comment]
The fix has to be applied to `tsconfig.json` of this plugin "nativescript-urlhandler
", not to the one in the app project.
See: https://docs.nativescript.org/best-practices/bundling-with-webpack#emitting-helper-functions-in-typescript-plugins

@hypery2k 
Thx for this plugin.
Can you release a new version of the plugin with the flag `"noEmitHelpers": true` set in `tsconfig.json` ?

**Comment by marksutt** [comment]
Thx for the quick fix.
When have you planned to release a new version containing this fix?

**Comment by hypery2k** [comment]
Not yet, having issues with my ci build

**Comment by hypery2k** [comment]
you can give `nativescript-urlhandler@1.2.1-develop-91` a try
