### ISSUE TITLE
Intent data is null when resuming app

### ISSUE THREAD

**Issue by mcrvaz** [hypery2k/nativescript-urlhandler#58]
Platform: Android

As explained is this [comment](https://github.com/NativeScript/NativeScript/issues/3738#issuecomment-284641303), when the application is already opened and the user attempts to reopen it with the deep link, the intent data is not updated.

**Comment by hypery2k** [comment]
could you please retry with version 1.2.0?

**Comment by uelipeter** [comment]
@hypery2k Why was this closed? I have the same issue on 1.2.0.

**Comment by hypery2k** [comment]
Thought it was solved. You can re-open it, but I don’t have time for this. Any PR is welcome

**Comment by one-adam-nolan** [comment]
I am having this same issue when using the [advanced-webview](https://github.com/bradmartin/nativescript-advanced-webview) library.  It redirects back to the app wonderfully, but the url (the part i need to parse) is not there.  Have you had a chance to look into it? I will take a look and see if I can contribute in anyway.  

Thanks!

**Comment by one-adam-nolan** [comment]
**Update:**
I deleted my node_modules folder then did a clean build and everything seemed to work.  I am wondering if this has something to do with the deployed code not updating the manifest properly- or something like that....
