### ISSUE TITLE
Angular: No callback provided

### ISSUE THREAD

**Issue by b-hobbs** [hypery2k/nativescript-urlhandler#70]
Following the setup guide, setting up the handler in the application component seemed to be too late, receiving: No callback provided. Please ensure that you called "handleOpenURL" during application init! 

I tried to look at the angular-demo but couldn't find any mention of handleOpenUrl. Is that just an unfinished place holder at the moment or was there something I missed?

Adding the handler in main.ts seemed to log the expected results but it is not the ideal place to have it.

**Comment by b-hobbs** [comment]
Moving it from the constructor to an ngOnInit of the application component also works as expected.

**Comment by hypery2k** [comment]
thanks for the hint, I'll add it to readme and sample angular app
