### ISSUE TITLE
Callback never called on iOS

### ISSUE THREAD

**Issue by pboulch** [hypery2k/nativescript-urlhandler#77]
Hi ! I tried to use this plugin for my deep links. On ANdroid no problem, it's work. But on iOS the callback is never called. I followed the instructions : change Info.plist, call handleOpenURL into the app.component.ts (into ngOnInit). 

Did I miss something ?

**Comment by hypery2k** [comment]
would be great if you tell more about your setup, version info and other plugins used etc.

**Comment by pboulch** [comment]
Ok, I found the problem. I use the WonderPush plugin, and, with iOS, it override the delegate.

**Comment by hypery2k** [comment]
ok, so it's a duplicate of #24
