### ISSUE TITLE
App URL doesn't work on Android

### ISSUE THREAD

**Issue by MustafaCa** [hypery2k/nativescript-urlhandler#79]
Hi Martin,

First of all, thank you for sharing this plug-in. I have implemented it successfully in IOS. However, I couldn't make it work on Android. Then, I tried your demo app and got the same result. It only works on IOS.

Thanks in advance for your support.

OS --> Mac

**NativeScript version:**
4.2.4

**Java version:**
1.8.0_181-b13

**NodeJS and NPM version:**
10.10 / 6.4.1

**Platform(s) running:**
IOS -> Runs fine on Emulator
Android -> Fails on Emulator

## Demo Project
The Demo project in this repo

**Comment by hypery2k** [comment]
fixed in 1.2.3
