### ISSUE TITLE
nativescript-Urlhandler not working in iOS.

### ISSUE THREAD

**Issue by rohitchindarkar** [hypery2k/nativescript-urlhandler#80]
not able to call below function in iOS  ,but its working fine in android.
handleOpenURL((appURL: AppURL) => {
      console.log( appURL);
}
can anyone help please...

**Comment by hypery2k** [comment]
fixed in 1.2.3

**Comment by ryanlangton** [comment]
I have 1.2.3 installed and I have the same issue, nothing is happening on handleOpenURL in iOS, works fine in android.

`
import { Component, OnInit } from "@angular/core";
import { handleOpenURL, AppURL } from 'nativescript-urlhandler';
import { AuthService } from "./core/services/auth-service";

@Component({
    moduleId: module.id,
    selector: "ns-app",
    templateUrl: "app.component.html"
})
export class AppComponent implements OnInit {
    constructor(private auth: AuthService) {}

    ngOnInit() {
        console.log('Vegan beacon initialized!');
        handleOpenURL((appURL: AppURL) => {
            console.log('Got the following appURL', appURL);
            const token = appURL.params['token'];
            console.log('path: ' + appURL.path);
            this.auth.login(token);
        });
    }
}
`
