### ISSUE TITLE
not working properly when app is closed

### ISSUE THREAD

**Issue by karo-dc** [hypery2k/nativescript-urlhandler#82]
when app is active deep handler works well, but when it's closed (terminated) it does not redirect to intended page, it only opens the app.

**Comment by sbacon94** [comment]
Hi there.

We are having the same problem. The callback is called when the app is already running in the background but is never called on launch.

**Comment by hypery2k** [comment]
does this happen on Android or iOS?

**Comment by hypery2k** [comment]
fixed in 1.2.3
